### PR TITLE
Raise useful error if no DatabaseCleaner strategies are loaded

### LINKED ISSUE #491: Breaks with database_cleaner 2.0
## Summary

When upgrading from database_cleaner 1.8 to 2.0, 

## Expected Behavior

cucumber-rails works in combination with database_cleaner 2.0.

## Current Behavior

I get the following error when a `@javascript` scenario is started:
~~~
undefined method `strategy' for nil:NilClass (NoMethodError)
~~~

This seems to be coming from https://github.com/cucumber/cucumber-rails/blob/master/lib/cucumber/rails/database/strategy.rb#L11.

## Possible Solution

I see two options:

- Figure out where database_cleaner 2.0 stores the current strategy, if not in `DatabaseCleaner.cleaners`.
- Use *two* configuration options instead of one, and create `Before` blocks like so:
  ```
  Before '@javascript' do
    DatabaseCleaner.strategy = Cucumber::Rails::Database.javascript_strategy
  end

  Before 'not @javascript' do
    DatabaseCleaner.strategy = Cucumber::Rails::Database.plain_strategy
  end
  ```

The latter option avoids having to use non-documented DatabaseCleaner APIs yet again.

## Steps to Reproduce (for bugs)

1. Have a Rails app with javascript scenarios, cucumber-rails, and database_cleaner 1.8.
2. Upgrade database_cleaner to 2.0
3. Run the cukes

## Context & Motivation

This came up when Dependabot tried to upgrade database_cleaner in my work projects.

## Your Environment

* Version used: 2.2.0
* Operating System and version: Debian, unstable
* Link to your project: N/A

### PR DESCRIPTION
**Pull request by mvz**
## Summary

Raise useful error if no DatabaseCleaner strategies are loaded

## Details

When `#before_js` is called on a Strategy, bail out if DatabaseCleaner.cleaners is empty.

## Motivation and Context

This fixes #491.

## How Has This Been Tested?

I added a spec and made it pass.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [x] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: spec/cucumber/rails/database_spec.rb [hunk 1]
```diff
@@ -1,18 +1,15 @@
...
 require 'cucumber/rails/database'
 
 describe Cucumber::Rails::Database do
-  before { allow(strategy_type).to receive(:new).and_return(strategy) }
-
-  let(:strategy) { instance_double(strategy_type, before_js: nil, before_non_js: nil) }
-  let(:strategy_type) { Cucumber::Rails::Database::TruncationStrategy }
-
   context 'when using a valid pre-determined strategy' do
+    let(:strategy) { described_class.instance_eval { @strategy } }
```
Comment (luke-hill) [inline spec/cucumber/rails/database_spec.rb:12]: Not sure for the idea for changing the specs around?

Comment (mvz) [reply spec/cucumber/rails/database_spec.rb:12]: I changed this so the specs will use a real strategy instance instead of an `instance_double`.

Comment (luke-hill) [reply spec/cucumber/rails/database_spec.rb:12]: I've dug in and think I can spot why it was weird. Just not keen on instance_eval in specs. But I see it's because we don't allow people to access the strategy value from the specification.

In that case it's all fine. You can move up the strategy let from both blocks to avoid duplication, but other than that it's good.

**Review by orien — APPROVED** [review]

**Comment by luke-hill** [comment]
I can re-review this by monday/tuesday. If you think it's still relevant (Just been off for a while).

**Review by luke-hill — APPROVED** [review]
